apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatinfra
spec:
  replicas: 1
  template:
    metadata:
      name: tomcatinfra
      labels:
        app: tomcatinfra
    spec:
      containers:
      - name: tomcatapp
        image: harsha2018/tomcat1:latest
